const Footer = () => {
  const footerStyle = {
    padding: '1rem',
    textAlign: 'center',
    color: 'white',
    marginTop: 'auto',
  };

  return (
    <footer style={footerStyle} className="bg-dark-brown">
      <p>&copy; footer</p>
      <small>Design generated by Google Stitch.</small>
    </footer>
  );
};

export default Footer;