import { render, screen } from '@testing-library/react';
import { describe, it, expect } from 'vitest';
import Footer from './Footer';

describe('Footer Component', () => {
  it('should render the copyright text', () => {
    render(<Footer />);
    
    const copyrightText = screen.getByText(/© footer/i);
    expect(copyrightText).toBeTruthy();
  });

  it('should display the design credit', () => {
    render(<Footer />);
    
    const creditText = screen.getByText(/Design generated by Google Stitch/i);
    expect(creditText).toBeTruthy();
    expect(creditText.tagName).toBe('SMALL');
  });

  it('should have the correct background class', () => {
    const { container } = render(<Footer />);
    const footerElement = container.querySelector('footer');
    
    expect(footerElement.classList.contains('bg-dark-brown')).toBe(true);
  });
});