import { render, screen } from '@testing-library/react';
import { describe, it, expect } from 'vitest';
import Footer from './Footer';

describe('Footer Component', () => {
  it('should render the creator name and copyright', () => {
    render(<Footer />);
    
    const creatorText = screen.getByText(/Andreea Aldea/i);
    expect(creatorText).toBeTruthy();
    
    const copyrightSymbol = screen.getByText(/©/i);
    expect(copyrightSymbol).toBeTruthy();
  });

  it('should display the design credit', () => {
    render(<Footer />);
    
    const creditText = screen.getByText(/Design generated by Google Stitch/i);
    expect(creditText).toBeTruthy();
    expect(creditText.tagName).toBe('SMALL');
  });

  it('should have a functional link to the GitHub repository', () => {
    render(<Footer />);
    
    const githubLink = screen.getByRole('link', { name: /Andreea Aldea/i });
    expect(githubLink).toBeTruthy();
    expect(githubLink.getAttribute('href')).toBe('https://github.com/andreeagaldea/landing_coffee_react');
    expect(githubLink.getAttribute('target')).toBe('_blank');
  });

  it('should have the correct background class', () => {
    const { container } = render(<Footer />);
    const footerElement = container.querySelector('footer');
    
    expect(footerElement?.classList.contains('bg-dark-brown')).toBe(true);
  });
});