import { FaGithub } from 'react-icons/fa';

const Footer = () => {
  const footerStyle = {
    padding: '2rem 1rem',
    textAlign: 'center',
    color: 'white',
    marginTop: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
    alignItems: 'center'
  };

  const linkStyle = {
    color: '#D1D5DB',
    textDecoration: 'none',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.5rem',
    transition: 'color 0.3s ease'
  };

  return (
    <footer style={footerStyle} className="bg-dark-brown">
      <p>&copy; {new Date().getFullYear()} Coffee Landing Page</p>
      
      <div style={{ marginBottom: '0.5rem' }}>
        <a 
          href="https://github.com/andreeagaldea/landing_coffee_react" 
          target="_blank" 
          rel="noopener noreferrer"
          style={linkStyle}
          onMouseOver={(e) => e.currentTarget.style.color = 'white'}
          onMouseOut={(e) => e.currentTarget.style.color = '#D1D5DB'}
        >
          <FaGithub size={20} />
          <span>Created by <strong>Andreea Aldea</strong></span>
        </a>
      </div>

      <small style={{ opacity: 0.8 }}>Design generated by Google Stitch.</small>
    </footer>
  );
};

export default Footer;